import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

// ─────────────────────────────────────────────────────────────────────────────
// FolioSense — Portfolio Snapshot PDF generator
//
// Builds a branded, single-call PDF report from the analysis object returned by
// analyzePortfolio() plus the raw positions array. Everything runs in the
// browser: no server, no holdings ever leave the user's device.
//
// Usage:
//   import { generatePortfolioPdf } from "../utils/generatePortfolioPdf";
//   generatePortfolioPdf(analysis, positions, "en");
// ─────────────────────────────────────────────────────────────────────────────

// Brand palette (RGB)
const GREEN = [26, 107, 74]; // #1a6b4a
const GOLD = [201, 153, 58]; // #c9993a
const RED = [192, 57, 43]; // #c0392b
const INK = [31, 41, 55]; // dark slate
const MUTED = [120, 120, 120];
const LIGHT = [240, 244, 242]; // soft green-gray fill
const LINE = [225, 225, 225];

// All report text lives here so the PDF is bilingual without touching useLang.
const L = {
  en: {
    subtitle: "Portfolio Snapshot",
    generated: "Generated",
    summary: "Summary",
    total_value: "Total value",
    assets: "Assets",
    max_concentration: "Max. concentration",
    risk_score: "Risk score",
    risk_high: "High",
    risk_mid: "Moderate",
    risk_low: "Low",
    sector_alloc: "Sector allocation",
    insights: "Insights",
    holdings: "Holdings",
    col_symbol: "Symbol",
    col_shares: "Shares",
    col_price: "Price",
    col_value: "Value",
    col_weight: "Weight",
    col_sector: "Sector",
    col_roi: "ROI",
    disclaimer:
      "For educational purposes only. Not financial advice. Generated by FolioSense.",
    notes: {
      note_no_positions: "No positions received.",
      note_high_concentration: "High concentration (>40%) in a single asset.",
      note_low_diversification:
        "Low diversification. Consider adding more assets.",
      note_good_balance: "Good overall balance.",
      note_sp500_anchored:
        "A significant portion is in S&P 500 ETFs, providing broad built-in diversification.",
      note_dead_weight:
        "You have losing positions with significant weight. Consider reviewing them.",
    },
  },
  es: {
    subtitle: "Resumen de tu portafolio",
    generated: "Generado",
    summary: "Resumen",
    total_value: "Valor total",
    assets: "Activos",
    max_concentration: "Concentración máx.",
    risk_score: "Puntaje de riesgo",
    risk_high: "Alto",
    risk_mid: "Moderado",
    risk_low: "Bajo",
    sector_alloc: "Asignación por sector",
    insights: "Observaciones",
    holdings: "Posiciones",
    col_symbol: "Símbolo",
    col_shares: "Cantidad",
    col_price: "Precio",
    col_value: "Valor",
    col_weight: "Peso",
    col_sector: "Sector",
    col_roi: "ROI",
    disclaimer:
      "Solo con fines educativos. No es asesoría financiera. Generado por FolioSense.",
    notes: {
      note_no_positions: "No se recibieron posiciones.",
      note_high_concentration: "Alta concentración (>40%) en un solo activo.",
      note_low_diversification:
        "Poca diversificación. Considera agregar más activos.",
      note_good_balance: "Buen balance general.",
      note_sp500_anchored:
        "Una parte significativa está en ETFs del S&P 500, lo que aporta diversificación amplia integrada.",
      note_dead_weight:
        "Tienes posiciones en pérdida con un peso significativo. Considera revisarlas.",
    },
  },
};

function fmtMoney(v, lang) {
  return new Intl.NumberFormat(lang === "es" ? "es-ES" : "en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(v || 0);
}

function fmtPct(v) {
  return (v * 100).toFixed(1) + "%";
}

function riskColor(score) {
  if (score >= 70) return RED;
  if (score >= 40) return GOLD;
  return GREEN;
}

function riskLabel(score, t) {
  if (score >= 70) return t.risk_high;
  if (score >= 40) return t.risk_mid;
  return t.risk_low;
}

export function generatePortfolioPdf(analysis, positions, lang = "en") {
  const t = L[lang] || L.en;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth(); // 210
  const M = 15; // margin
  const contentW = pageW - M * 2;

  // ── Header band ────────────────────────────────────────────────────────────
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, pageW, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("FolioSense", M, 13);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(t.subtitle, M, 21);

  const dateStr = new Date().toLocaleDateString(
    lang === "es" ? "es-ES" : "en-US",
    { year: "numeric", month: "long", day: "numeric" },
  );
  doc.setFontSize(9);
  doc.text(`${t.generated}: ${dateStr}`, pageW - M, 13, { align: "right" });

  let y = 40;

  // ── Summary stat boxes ───────────────────────────────────────────────────
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(t.summary, M, y);
  y += 4;

  const boxGap = 4;
  const boxW = (contentW - boxGap * 3) / 4;
  const boxH = 20;
  const stats = [
    { label: t.total_value, value: fmtMoney(analysis.totalValue, lang) },
    { label: t.assets, value: String(analysis.diversification ?? 0) },
    {
      label: t.max_concentration,
      value: fmtPct(analysis.concentration || 0),
    },
    { label: t.risk_score, value: String(analysis.riskScore ?? 0) },
  ];

  stats.forEach((s, i) => {
    const x = M + i * (boxW + boxGap);
    doc.setFillColor(...LIGHT);
    doc.roundedRect(x, y, boxW, boxH, 2, 2, "F");
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.text(s.label.toUpperCase(), x + 4, y + 7);
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(s.value, x + 4, y + 15);
  });
  y += boxH + 12;

  // ── Risk meter ───────────────────────────────────────────────────────────
  const score = Math.max(0, Math.min(100, analysis.riskScore || 0));
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(
    `${t.risk_score}: ${score} (${riskLabel(score, t)})`,
    M,
    y,
  );
  y += 4;
  const barH = 5;
  doc.setFillColor(...LINE);
  doc.roundedRect(M, y, contentW, barH, 1.5, 1.5, "F");
  doc.setFillColor(...riskColor(score));
  doc.roundedRect(M, y, (contentW * score) / 100, barH, 1.5, 1.5, "F");
  y += barH + 12;

  // ── Sector allocation bars ─────────────────────────────────────────────────
  const sectors = Object.entries(analysis.sectors || {})
    .map(([name, info]) => ({ name, value: info.value || 0 }))
    .sort((a, b) => b.value - a.value);

  if (sectors.length > 0) {
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(t.sector_alloc, M, y);
    y += 6;

    const labelW = 50;
    const barMaxW = contentW - labelW - 22;
    const maxVal = sectors[0].value || 1;
    const total = analysis.totalValue || 1;

    sectors.forEach((s, i) => {
      const barLen = Math.max(1.5, (s.value / maxVal) * barMaxW);
      doc.setTextColor(...INK);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      const name = s.name.length > 24 ? s.name.slice(0, 22) + "…" : s.name;
      doc.text(name, M, y + 3);
      doc.setFillColor(...(i === 0 ? GOLD : GREEN));
      doc.roundedRect(M + labelW, y, barLen, 4, 1, 1, "F");
      doc.setTextColor(...MUTED);
      doc.text(fmtPct(s.value / total), M + labelW + barLen + 2, y + 3);
      y += 7;
    });
    y += 6;
  }

  // ── Insights ───────────────────────────────────────────────────────────────
  const notes = (analysis.noteKeys || [])
    .map((k) => t.notes[k])
    .filter(Boolean);

  if (notes.length > 0) {
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(t.insights, M, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    notes.forEach((n) => {
      const lines = doc.splitTextToSize(`•  ${n}`, contentW);
      doc.setTextColor(...INK);
      doc.text(lines, M, y);
      y += lines.length * 5 + 1;
    });
    y += 6;
  }

  // ── Holdings table ───────────────────────────────────────────────────────
  const rows = [...(positions || [])]
    .sort((a, b) => (b.value || 0) - (a.value || 0))
    .map((p) => {
      const weight = analysis.totalValue
        ? (p.value || 0) / analysis.totalValue
        : 0;
      return [
        p.symbol || "—",
        String(p.shares ?? "—"),
        fmtMoney(p.price, lang),
        fmtMoney(p.value, lang),
        fmtPct(weight),
        p.sector || "—",
        p.roi != null ? (p.roi * 100).toFixed(1) + "%" : "—",
      ];
    });

  autoTable(doc, {
    startY: y,
    head: [
      [
        t.col_symbol,
        t.col_shares,
        t.col_price,
        t.col_value,
        t.col_weight,
        t.col_sector,
        t.col_roi,
      ],
    ],
    body: rows,
    margin: { left: M, right: M },
    styles: { font: "helvetica", fontSize: 8.5, cellPadding: 2 },
    headStyles: { fillColor: GREEN, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 249] },
    columnStyles: {
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      6: { halign: "right" },
    },
    // Color ROI column red/green based on sign
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 6) {
        const txt = data.cell.raw;
        if (typeof txt === "string" && txt.includes("-")) {
          data.cell.styles.textColor = RED;
        } else if (typeof txt === "string" && txt.includes("%")) {
          data.cell.styles.textColor = GREEN;
        }
      }
    },
  });

  // ── Footer on every page ───────────────────────────────────────────────────
  const pageCount = doc.internal.getNumberOfPages();
  const pageH = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...LINE);
    doc.line(M, pageH - 14, pageW - M, pageH - 14);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.text(t.disclaimer, M, pageH - 9);
    doc.text("foliosenseapp.com", pageW - M, pageH - 9, { align: "right" });
    doc.text(`${i} / ${pageCount}`, pageW / 2, pageH - 9, { align: "center" });
  }

  const today = new Date().toISOString().slice(0, 10);
  doc.save(`FolioSense-Portfolio-Snapshot-${today}.pdf`);
}
