import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";

// ─────────────────────────────────────────────────────────────────────────────
// FolioSense — Portfolio Snapshot PDF generator
//
// Header, summary stats, risk meter, the sector comparison, and the holdings
// table are drawn as crisp vector. The remaining dashboard charts (distribution,
// radar, scatter, rankings) are captured live from the DOM (elements tagged
// data-pdf-chart) and embedded as images.
//
// Everything runs in the browser: no server, no holdings ever leave the device.
//
// Usage (async):
//   await generatePortfolioPdf(analysis, positions, "en");
// ─────────────────────────────────────────────────────────────────────────────

// Brand palette (RGB)
const GREEN = [26, 107, 74]; // #1a6b4a
const GOLD = [201, 153, 58]; // #c9993a
const RED = [192, 57, 43]; // #c0392b
const INK = [31, 41, 55]; // dark slate
const MUTED = [120, 120, 120];
const LIGHT = [240, 244, 242]; // soft green-gray fill
const LINE = [225, 225, 225];

// All report text lives here so the PDF is bilingual without touching useLang.
const L = {
  en: {
    subtitle: "Portfolio Snapshot",
    generated: "Generated",
    summary: "Summary",
    total_value: "Total value",
    assets: "Assets",
    max_concentration: "Max. concentration",
    risk_score: "Risk score",
    risk_high: "High",
    risk_mid: "Moderate",
    risk_low: "Low",
    insights: "Insights",
    charts_heading: "Visual analysis",
    sectors_heading: "Sector exposure vs S&P 500",
    you_label: "You",
    sp_label: "S&P 500",
    overweight: "Overweight",
    underweight: "Underweight",
    inline_label: "In line",
    holdings: "Holdings",
    col_symbol: "Symbol",
    col_shares: "Shares",
    col_price: "Price",
    col_value: "Value",
    col_weight: "Weight",
    col_sector: "Sector",
    col_roi: "ROI",
    disclaimer:
      "For educational purposes only. Not financial advice. Generated by FolioSense.",
    notes: {
      note_no_positions: "No positions received.",
      note_high_concentration: "High concentration (>40%) in a single asset.",
      note_low_diversification:
        "Low diversification. Consider adding more assets.",
      note_good_balance: "Good overall balance.",
      note_sp500_anchored:
        "A significant portion is in S&P 500 ETFs, providing broad built-in diversification.",
      note_dead_weight:
        "You have losing positions with significant weight. Consider reviewing them.",
    },
  },
  es: {
    subtitle: "Resumen de tu portafolio",
    generated: "Generado",
    summary: "Resumen",
    total_value: "Valor total",
    assets: "Activos",
    max_concentration: "Concentración máx.",
    risk_score: "Puntaje de riesgo",
    risk_high: "Alto",
    risk_mid: "Moderado",
    risk_low: "Bajo",
    insights: "Observaciones",
    charts_heading: "Análisis visual",
    sectors_heading: "Exposición por sector vs S&P 500",
    you_label: "Tú",
    sp_label: "S&P 500",
    overweight: "Sobreponderado",
    underweight: "Infraponderado",
    inline_label: "En línea",
    holdings: "Posiciones",
    col_symbol: "Símbolo",
    col_shares: "Cantidad",
    col_price: "Precio",
    col_value: "Valor",
    col_weight: "Peso",
    col_sector: "Sector",
    col_roi: "ROI",
    disclaimer:
      "Solo con fines educativos. No es asesoría financiera. Generado por FolioSense.",
    notes: {
      note_no_positions: "No se recibieron posiciones.",
      note_high_concentration: "Alta concentración (>40%) en un solo activo.",
      note_low_diversification:
        "Poca diversificación. Considera agregar más activos.",
      note_good_balance: "Buen balance general.",
      note_sp500_anchored:
        "Una parte significativa está en ETFs del S&P 500, lo que aporta diversificación amplia integrada.",
      note_dead_weight:
        "Tienes posiciones en pérdida con un peso significativo. Considera revisarlas.",
    },
  },
};

function fmtMoney(v, lang) {
  return new Intl.NumberFormat(lang === "es" ? "es-ES" : "en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(v || 0);
}

function fmtPct(v) {
  return (v * 100).toFixed(1) + "%";
}

function riskColor(score) {
  if (score >= 70) return RED;
  if (score >= 40) return GOLD;
  return GREEN;
}

function riskLabel(score, t) {
  if (score >= 70) return t.risk_high;
  if (score >= 40) return t.risk_mid;
  return t.risk_low;
}

export async function generatePortfolioPdf(analysis, positions, lang = "en") {
  const t = L[lang] || L.en;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth(); // 210
  const pageH = doc.internal.pageSize.getHeight(); // 297
  const M = 15; // margin
  const contentW = pageW - M * 2;
  const FOOTER_SPACE = 18; // reserved bottom margin
  const NEW_PAGE_TOP = 20; // top start for added pages

  // ── Header band ────────────────────────────────────────────────────────────
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, pageW, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("FolioSense", M, 13);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(t.subtitle, M, 21);

  const dateStr = new Date().toLocaleDateString(
    lang === "es" ? "es-ES" : "en-US",
    { year: "numeric", month: "long", day: "numeric" },
  );
  doc.setFontSize(9);
  doc.text(`${t.generated}: ${dateStr}`, pageW - M, 13, { align: "right" });

  let y = 40;

  // ── Summary stat boxes ───────────────────────────────────────────────────
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(t.summary, M, y);
  y += 4;

  const boxGap = 4;
  const boxW = (contentW - boxGap * 3) / 4;
  const boxH = 20;
  const stats = [
    { label: t.total_value, value: fmtMoney(analysis.totalValue, lang) },
    { label: t.assets, value: String(analysis.diversification ?? 0) },
    { label: t.max_concentration, value: fmtPct(analysis.concentration || 0) },
    { label: t.risk_score, value: String(analysis.riskScore ?? 0) },
  ];

  stats.forEach((s, i) => {
    const x = M + i * (boxW + boxGap);
    doc.setFillColor(...LIGHT);
    doc.roundedRect(x, y, boxW, boxH, 2, 2, "F");
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.text(s.label.toUpperCase(), x + 4, y + 7);
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(s.value, x + 4, y + 15);
  });
  y += boxH + 12;

  // ── Risk meter ───────────────────────────────────────────────────────────
  const score = Math.max(0, Math.min(100, analysis.riskScore || 0));
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`${t.risk_score}: ${score} (${riskLabel(score, t)})`, M, y);
  y += 4;
  const barH = 5;
  doc.setFillColor(...LINE);
  doc.roundedRect(M, y, contentW, barH, 1.5, 1.5, "F");
  doc.setFillColor(...riskColor(score));
  doc.roundedRect(M, y, (contentW * score) / 100, barH, 1.5, 1.5, "F");
  y += barH + 12;

  // ── Insights ───────────────────────────────────────────────────────────────
  const notes = (analysis.noteKeys || [])
    .map((k) => t.notes[k])
    .filter(Boolean);

  if (notes.length > 0) {
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(t.insights, M, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    notes.forEach((n) => {
      const lines = doc.splitTextToSize(`•  ${n}`, contentW);
      doc.setTextColor(...INK);
      doc.text(lines, M, y);
      y += lines.length * 5 + 1;
    });
    y += 8;
  }

  // ── Visual analysis heading ─────────────────────────────────────────────────
  const sectorRows = Object.entries(analysis.sectorVsSP500 || {})
    .map(([name, d]) => ({ name, ...d }))
    .filter((d) => (d.userPct || 0) > 0 || (d.sp500Pct || 0) > 0)
    .sort((a, b) => (b.userPct || 0) - (a.userPct || 0));

  const nodes = Array.from(document.querySelectorAll("[data-pdf-chart]"));

  if (sectorRows.length > 0 || nodes.length > 0) {
    if (y + 14 > pageH - FOOTER_SPACE) {
      doc.addPage();
      y = NEW_PAGE_TOP;
    }
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(t.charts_heading, M, y);
    y += 8;
  }

  // ── Sector exposure vs S&P 500 (native vector) ─────────────────────────────
  if (sectorRows.length > 0) {
    if (y + 12 > pageH - FOOTER_SPACE) {
      doc.addPage();
      y = NEW_PAGE_TOP;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...INK);
    doc.text(t.sectors_heading, M, y);
    y += 7;

    const maxPct = Math.max(
      ...sectorRows.map((d) => Math.max(d.userPct || 0, d.sp500Pct || 0)),
      1,
    );
    const barX = M + 16;
    const barMaxW = contentW - 16 - 12; // leave room for right-aligned % labels
    const sBarH = 3;

    sectorRows.forEach((d) => {
      const rowH = 18;
      if (y + rowH > pageH - FOOTER_SPACE) {
        doc.addPage();
        y = NEW_PAGE_TOP;
      }

      // Sector name (left) + delta label (right)
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...INK);
      doc.text(d.name, M, y);

      const delta = d.delta || 0;
      let word;
      let col;
      if (delta >= 1) {
        word = `+${delta}% ${t.overweight}`;
        col = GREEN;
      } else if (delta <= -1) {
        word = `${delta}% ${t.underweight}`;
        col = RED;
      } else {
        word = t.inline_label;
        col = MUTED;
      }
      doc.setFontSize(8);
      doc.setTextColor(...col);
      doc.text(word, M + contentW, y, { align: "right" });
      y += 3.5;

      // "You" bar
      doc.setFont("helvetica", "normal");
      doc.setFontSize(6.5);
      doc.setTextColor(...MUTED);
      doc.text(t.you_label, M, y + sBarH - 0.6);
      doc.setFillColor(...LINE);
      doc.roundedRect(barX, y, barMaxW, sBarH, 0.8, 0.8, "F");
      doc.setFillColor(...GREEN);
      doc.roundedRect(
        barX,
        y,
        Math.max(0.5, ((d.userPct || 0) / maxPct) * barMaxW),
        sBarH,
        0.8,
        0.8,
        "F",
      );
      doc.setTextColor(...INK);
      doc.text(`${d.userPct || 0}%`, M + contentW, y + sBarH - 0.6, {
        align: "right",
      });
      y += sBarH + 2;

      // "S&P 500" bar
      doc.setTextColor(...MUTED);
      doc.text(t.sp_label, M, y + sBarH - 0.6);
      doc.setFillColor(...LINE);
      doc.roundedRect(barX, y, barMaxW, sBarH, 0.8, 0.8, "F");
      doc.setFillColor(...GOLD);
      doc.roundedRect(
        barX,
        y,
        Math.max(0.5, ((d.sp500Pct || 0) / maxPct) * barMaxW),
        sBarH,
        0.8,
        0.8,
        "F",
      );
      doc.setTextColor(...INK);
      doc.text(`${d.sp500Pct || 0}%`, M + contentW, y + sBarH - 0.6, {
        align: "right",
      });
      y += sBarH + 6;
    });
    y += 2;
  }

  // ── Captured charts (distribution, radar, scatter, rankings) ───────────────
  if (nodes.length > 0) {
    try {
      if (document.fonts && document.fonts.ready) await document.fonts.ready;
    } catch (e) {
      /* ignore */
    }

    const maxChartH = 110; // mm — keep any single chart from dominating a page

    for (const node of nodes) {
      let canvas;
      try {
        canvas = await html2canvas(node, {
          scale: 2,
          backgroundColor: "#ffffff",
          useCORS: true,
          logging: false,
        });
      } catch (e) {
        console.warn("Chart capture skipped:", e);
        continue;
      }

      const img = canvas.toDataURL("image/png");
      let w = contentW;
      let h = (canvas.height / canvas.width) * w;
      if (h > maxChartH) {
        h = maxChartH;
        w = (canvas.width / canvas.height) * h;
      }
      const x = M + (contentW - w) / 2;

      if (y + h > pageH - FOOTER_SPACE) {
        doc.addPage();
        y = NEW_PAGE_TOP;
      }
      doc.addImage(img, "PNG", x, y, w, h);
      y += h + 8;
    }
  }

  // ── Holdings table ───────────────────────────────────────────────────────
  const rows = [...(positions || [])]
    .sort((a, b) => (b.value || 0) - (a.value || 0))
    .map((p) => {
      const weight = analysis.totalValue
        ? (p.value || 0) / analysis.totalValue
        : 0;
      return [
        p.symbol || "—",
        String(p.shares ?? "—"),
        fmtMoney(p.price, lang),
        fmtMoney(p.value, lang),
        fmtPct(weight),
        p.sector || "—",
        p.roi != null ? (p.roi * 100).toFixed(1) + "%" : "—",
      ];
    });

  if (y + 24 > pageH - FOOTER_SPACE) {
    doc.addPage();
    y = NEW_PAGE_TOP;
  }
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(t.holdings, M, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [
      [
        t.col_symbol,
        t.col_shares,
        t.col_price,
        t.col_value,
        t.col_weight,
        t.col_sector,
        t.col_roi,
      ],
    ],
    body: rows,
    margin: { left: M, right: M },
    styles: { font: "helvetica", fontSize: 8.5, cellPadding: 2 },
    headStyles: {
      fillColor: GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [248, 250, 249] },
    columnStyles: {
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      6: { halign: "right" },
    },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 6) {
        const txt = data.cell.raw;
        if (typeof txt === "string" && txt.includes("-")) {
          data.cell.styles.textColor = RED;
        } else if (typeof txt === "string" && txt.includes("%")) {
          data.cell.styles.textColor = GREEN;
        }
      }
    },
  });

  // ── Footer on every page ───────────────────────────────────────────────────
  // Disclaimer on the left, site + page number combined on the right, so the
  // page number never collides with the disclaimer text.
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...LINE);
    doc.line(M, pageH - 14, pageW - M, pageH - 14);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.text(t.disclaimer, M, pageH - 9);
    doc.text(
      `foliosenseapp.com  ·  ${i} / ${pageCount}`,
      pageW - M,
      pageH - 9,
      {
        align: "right",
      },
    );
  }

  const today = new Date().toISOString().slice(0, 10);
  doc.save(`FolioSense-Portfolio-Snapshot-${today}.pdf`);
}
